import io

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def generate_pdf(patient_name, patient_age, mri_result=None, speech_result=None, q_result=None):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=0.8 * inch, bottomMargin=0.8 * inch,
                             leftMargin=0.8 * inch, rightMargin=0.8 * inch)
    styles = getSampleStyleSheet()
    story = []

    title_s = ParagraphStyle("T", parent=styles["Title"], fontSize=18, textColor=colors.HexColor("#0A1628"), spaceAfter=4)
    sub_s = ParagraphStyle("S", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#64748B"))
    h2_s = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=12, textColor=colors.HexColor("#1E3A5F"), spaceBefore=12)

    story.append(Paragraph("NeuroAI — ASD Screening Report", title_s))
    story.append(Paragraph("AI-assisted multimodal ASD screening | For clinical support use only", sub_s))
    story.append(Spacer(1, 0.15 * inch))

    disc = ParagraphStyle("D", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#92400E"),
                           backColor=colors.HexColor("#FFFBEB"), borderPadding=6)
    story.append(Paragraph(
        "DISCLAIMER: This report is for research and clinical decision SUPPORT only. "
        "It does NOT constitute a medical diagnosis. All findings must be reviewed by a "
        "qualified healthcare professional.", disc))
    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("Patient Information", h2_s))
    pt = Table([
        ["Patient Name", patient_name or "Not provided"],
        ["Age", f"{patient_age} months"],
        ["Report Date", pd.Timestamp.now().strftime("%d %B %Y")],
        ["Generated By", "NeuroAI System"],
    ], colWidths=[2 * inch, 4 * inch])
    pt.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EFF6FF")),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
    ]))
    story.append(pt)

    if mri_result and mri_result.get("success"):
        story.append(Paragraph("MRI Brain Analysis", h2_s))
        pred = mri_result["prediction"]
        m_color = colors.HexColor("#FEE2E2") if pred == "ASD" else colors.HexColor("#DCFCE7")
        mt = Table([
            ["Prediction", pred],
            ["Confidence", f"{mri_result['confidence']*100:.1f}%"],
            ["ASD Probability", f"{mri_result['asd_prob']*100:.1f}%"],
            ["NonASD Probability", f"{mri_result['non_prob']*100:.1f}%"],
        ], colWidths=[2 * inch, 4 * inch])
        mt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), m_color),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ]))
        story.append(mt)

    if speech_result and speech_result.get("success"):
        story.append(Paragraph("Speech Prosody Analysis", h2_s))
        st_table = Table([
            ["Risk Level", speech_result["risk_level"]],
            ["Risk Score", f"{speech_result['risk_score']}/100"],
            ["Pitch Variance", f"{speech_result['pitch_std']:.1f} Hz"],
            ["Speech Activity", f"{speech_result['speech_ratio']*100:.0f}%"],
            ["Detected Flags", " | ".join(speech_result["flags"][:2])],
        ], colWidths=[2 * inch, 4 * inch])
        st_table.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ]))
        story.append(st_table)

    if q_result:
        story.append(Paragraph("Behavioural Screening", h2_s))
        q_color = {
            "Low Risk": colors.HexColor("#DCFCE7"),
            "Moderate Risk": colors.HexColor("#FEF3C7"),
            "High Risk": colors.HexColor("#FEE2E2"),
        }.get(q_result["level"], colors.white)
        qt = Table([
            ["Risk Level", q_result["level"]],
            ["Score", f"{q_result['score']}/{q_result['max']}"],
            ["Recommendation", q_result["rec"]],
        ], colWidths=[2 * inch, 4 * inch])
        qt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), q_color),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(qt)

    story.append(Spacer(1, 0.3 * inch))
    footer_s = ParagraphStyle("F", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#94A3B8"), alignment=1)
    story.append(Paragraph(
        "NeuroAI — Department of Information Technology | Academic Year 2025-26 | "
        "For research and clinical support use only", footer_s))

    doc.build(story)
    buf.seek(0)
    return buf
